"""S152-06a §4 — the server-side TipTap JSON → HTML renderer is a port of the SPA's.

``tests/fixtures/tiptap_parity.json`` holds TipTap docs and the HTML the SPA's
``CmsPageTypeBase.renderNode`` produces for them (generated by running a verbatim
JS copy of that function in node — fe-user ships no TipTap fixture of its own).
The Python port must produce exactly the same bytes.
"""
import json
from pathlib import Path

import pytest

from plugins.theme_cms.theme_cms.tiptap import render_tiptap_document

FIXTURE_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "tiptap_parity.json"
PARITY_CASES = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))["cases"]


@pytest.mark.parametrize(
    "case", PARITY_CASES, ids=[case["name"] for case in PARITY_CASES]
)
def test_matches_the_spa_render_node_byte_for_byte(case):
    assert render_tiptap_document(case["doc"]) == case["expected_html"]


@pytest.mark.parametrize("not_a_document", [None, {}, [], "text"])
def test_a_missing_or_non_object_document_renders_nothing(not_a_document):
    assert render_tiptap_document(not_a_document) == ""
